  <% default_args = "--publish-quiet --format AllureCucumber::CucumberFormatter --out allure-results --format pretty -c -t 'not @wip'"%>
  default: <%= default_args %> ENVIRONMENT=default SELENIUM_GRID=false
  browser: <%= default_args %> ENVIRONMENT=browser -t 'not @device-specific' -t 'not @slow' -t 'not @amazonfiretv' -t 'not @freeview' -t 'not @samsung'  -t 'not @sky' -t 'not @youview' -t 'not @virginmedia' -t 'not @virginmediativo'
  amazonfiretv: <%= default_args %> ENVIRONMENT=amazonfiretv -t @amazonfiretv
  samsung: <%= default_args %> ENVIRONMENT=samsung -t @samsung
  sky: <%= default_args %> ENVIRONMENT=sky -t @sky
  freeview: <%= default_args %> ENVIRONMENT=freeview -t @freeview
  youview: <%= default_args %> ENVIRONMENT=youview -t @youview
  virginmedia: <%= default_args %> ENVIRONMENT=virginmedia -t @virginmedia
  virginmediativo: <%= default_args %> ENVIRONMENT=virginmediativo -t @virginmediativo
  slow: <%= default_args %> ENVIRONMENT=browser -t @slow
  local: -p browser

  grid: SELENIUM_GRID=true --format json --out cucumber_report.json
  no_grid: SELENIUM_GRID=false

  generate_screenshots: IMAGE_DIFF=generate  <%= default_args %> ENVIRONMENT=local -p grid -t @visual_test
  visual_regression: IMAGE_DIFF=regression <%= default_args %> ENVIRONMENT=local -p grid -t @visual_test
