default:
  base_url: https://cassandra:5000/browser

local:
  base_url: https://cassandra:5000/browser

browser:
  base_url: https://cassandra:5000/browser

amazonfiretv:
  base_url: https://cassandra:5000/amazonfiretv

samsung:
  base_url: https://cassandra:5000/samsung

sky:
  base_url: https://cassandra:5000/sky


freeview:
  base_url: https://cassandra:5000/freeview

youview:
  base_url: https://cassandra:5000/youview

virginmedia:
  base_url: https://cassandra:5000/virginmedia

virginmediativo:
  base_url: https://cassandra:5000/virginmedia

stubs:
  advertisement_stub: https://advertisementstub:6789
  discovery_stub: https://discoverystub:5678
  usp_stub: https://uspstub:4567
  video_stub: https://viewing-test-harness:443


